// <auto-generated />
using System;
using Hossein.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hossein.Migrations
{
    [DbContext(typeof(EducationContext))]
    partial class EducationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hossein.Entities.CalendarCostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CalendarCostTypes", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Duty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Duties", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.EvaluationQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EvaluationQuestions", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Exam.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Exam.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Exam.TrainingCalendarQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TrainingCalendarId");

                    b.ToTable("TrainingCalendarQuestions", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Exam.TrainingCalendarQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<float?>("AnswerRate")
                        .HasColumnType("real");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCalendarQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TrainingCalendarQuestionId");

                    b.ToTable("TrainingCalendarQuestionAnswers", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Personels", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingCalendarId");

                    b.HasIndex("PersonelId", "TrainingCalendarId")
                        .IsUnique();

                    b.ToTable("PersonelTrainingCalendars", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CalendarCostTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonelTrainingCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalendarCostTypeId");

                    b.HasIndex("PersonelTrainingCalendarId");

                    b.ToTable("PersonelTrainingCalendarCosts", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonelTrainingCalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelTrainingCalendarId");

                    b.HasIndex("TeacherId");

                    b.ToTable("PersonelTrainingCalendarMeetings", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeetingAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PersonelTrainingCalendarMeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelTrainingCalendarMeetingId");

                    b.ToTable("PersonelTrainingCalendarMeetingAttachments", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelTrainingCalendarMeetingId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("PersonelTrainingCalendarMeetingId");

                    b.ToTable("PersonelTrainingCalendarMeetingAttendances", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeetingScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PersonelTrainingCalendarId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelTrainingCalendarId");

                    b.ToTable("PersonelTrainingCalendarMeetingScores", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PostDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DutyId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DutyId");

                    b.HasIndex("PostId", "DutyId")
                        .IsUnique();

                    b.ToTable("PostDuties", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PostTrainingStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingStandardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingStandardId");

                    b.HasIndex("PostId", "TrainingStandardId")
                        .IsUnique();

                    b.ToTable("PostTrainingStandards", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.PostTrainingStandardAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PostTrainingStandardId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PostTrainingStandardId");

                    b.ToTable("PostTrainingStandardAttachments", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TrainingCalendars", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingCalendarId");

                    b.ToTable("TrainingCalendarAttachments", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarEvaluationQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluationQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int?>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationQuestionId");

                    b.HasIndex("TrainingCalendarId");

                    b.ToTable("TrainingCalendarEvaluationQuestions", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarEvaluationQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrainingCalendarEvaluationQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingCalendarEvaluationQuestionId");

                    b.ToTable("TrainingCalendarEvaluationQuestionAnswers", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarPrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingStandardId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingCalendarId");

                    b.HasIndex("TrainingStandardId");

                    b.ToTable("TrainingCalendarPrerequisites", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingStandardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingStandardId");

                    b.HasIndex("TrainingCalendarId", "TrainingStandardId")
                        .IsUnique();

                    b.ToTable("TrainingCalendarStandards", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TrainingCalendarId", "TeacherId")
                        .IsUnique();

                    b.ToTable("TrainingCalendarTeachers", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TrainingStandards", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingStandardAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrainingStandardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingStandardId");

                    b.ToTable("TrainingStandardAttachments", (string)null);
                });

            modelBuilder.Entity("Hossein.Entities.Exam.QuestionOption", b =>
                {
                    b.HasOne("Hossein.Entities.Exam.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.Exam.TrainingCalendarQuestion", b =>
                {
                    b.HasOne("Hossein.Entities.Exam.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.Exam.TrainingCalendarQuestionAnswer", b =>
                {
                    b.HasOne("Hossein.Entities.Personel", null)
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.Exam.TrainingCalendarQuestion", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.Personel", b =>
                {
                    b.HasOne("Hossein.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendar", b =>
                {
                    b.HasOne("Hossein.Entities.Personel", null)
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarCost", b =>
                {
                    b.HasOne("Hossein.Entities.CalendarCostType", null)
                        .WithMany()
                        .HasForeignKey("CalendarCostTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.PersonelTrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("PersonelTrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeeting", b =>
                {
                    b.HasOne("Hossein.Entities.PersonelTrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("PersonelTrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeetingAttachment", b =>
                {
                    b.HasOne("Hossein.Entities.PersonelTrainingCalendarMeeting", null)
                        .WithMany()
                        .HasForeignKey("PersonelTrainingCalendarMeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeetingAttendance", b =>
                {
                    b.HasOne("Hossein.Entities.Personel", null)
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.PersonelTrainingCalendarMeeting", null)
                        .WithMany()
                        .HasForeignKey("PersonelTrainingCalendarMeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PersonelTrainingCalendarMeetingScore", b =>
                {
                    b.HasOne("Hossein.Entities.PersonelTrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("PersonelTrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PostDuty", b =>
                {
                    b.HasOne("Hossein.Entities.Duty", null)
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PostTrainingStandard", b =>
                {
                    b.HasOne("Hossein.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.TrainingStandard", null)
                        .WithMany()
                        .HasForeignKey("TrainingStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.PostTrainingStandardAttachment", b =>
                {
                    b.HasOne("Hossein.Entities.PostTrainingStandard", null)
                        .WithMany()
                        .HasForeignKey("PostTrainingStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendar", b =>
                {
                    b.HasOne("Hossein.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarAttachment", b =>
                {
                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarEvaluationQuestion", b =>
                {
                    b.HasOne("Hossein.Entities.EvaluationQuestion", null)
                        .WithMany()
                        .HasForeignKey("EvaluationQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarEvaluationQuestionAnswer", b =>
                {
                    b.HasOne("Hossein.Entities.TrainingCalendarEvaluationQuestion", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarEvaluationQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarPrerequisite", b =>
                {
                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hossein.Entities.TrainingStandard", null)
                        .WithMany()
                        .HasForeignKey("TrainingStandardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarStandard", b =>
                {
                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.TrainingStandard", null)
                        .WithMany()
                        .HasForeignKey("TrainingStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.TrainingCalendarTeacher", b =>
                {
                    b.HasOne("Hossein.Entities.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hossein.Entities.TrainingCalendar", null)
                        .WithMany()
                        .HasForeignKey("TrainingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hossein.Entities.TrainingStandardAttachment", b =>
                {
                    b.HasOne("Hossein.Entities.TrainingStandard", null)
                        .WithMany()
                        .HasForeignKey("TrainingStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
